# Generated by Django 3.2 on 2021-04-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=50)),
                ('scientific_name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('maintenance_level', models.CharField(max_length=50)),
                ('best_suited', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=1000)),
                ('decorative_bonus', models.PositiveIntegerField()),
                ('average_price', models.PositiveIntegerField()),
                ('categories', models.ManyToManyField(related_name='plants', to='categories.Categories')),
            ],
        ),
    ]
