# Generated by Django 3.2 on 2021-04-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=50)),
                ('scientific_name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('maintenance_level', models.CharField(max_length=50)),
                ('best_suited', models.CharField(max_length=50)),
                ('decorative_bonus', models.PositiveIntegerField()),
                ('average_price', models.PositiveIntegerField()),
            ],
        ),
    ]
