# Generated by Django 3.2 on 2021-04-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plnt',
            new_name='Plant',
        ),
    ]
