# Generated by Django 3.2 on 2021-04-16 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '0002_plant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plants', to=settings.AUTH_USER_MODEL),
        ),
    ]
