# Generated by Django 3.2 on 2021-04-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_alter_plant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='care_instructions',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
