# Generated by Django 3.2 on 2021-04-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_plant_care_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='care_instructions',
            field=models.CharField(max_length=1500),
        ),
    ]
