# Generated by Django 3.2 on 2021-04-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_alter_plant_care_instructions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='average_price',
            new_name='averageprice',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='best_suited',
            new_name='bestsuited',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='care_instructions',
            new_name='careinstructions',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='decorative_bonus',
            new_name='decorativebonus',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='maintenance_level',
            new_name='maintenancelevel',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='plant_name',
            new_name='plantname',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='scientific_name',
            new_name='scientificname',
        ),
    ]
